package com.rabyte.rabitdash.UI;

import com.rabyte.rabitdash.util.Constants;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class MainMenu {
    private static JFrame frame;
    private static JFrame jf;
    private static GamePanel gamePanel;
    private JPanel panel1;
    private JPanel bakPanel;
    private JButton startButton;
    private JButton exitButton;
    private JPanel panelBak;

    public MainMenu() {
        $$$setupUI$$$();
        exitButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                System.exit(0);
            }
        });
        startButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                frame.setVisible(false);
                jf.setVisible(true);
                gamePanel.setVisible(true);
                gamePanel.start();
                gamePanel.requestFocus();
//                System.out.println(gamePanel.requestFocusInWindow());
            }
        });

    }

    private static void initBakImage() {
//        mainBak = new ImageIcon(getClass().getResource("/resources/images/mainBak.jpg"))
//                .getImage()
//                .getScaledInstance(Constants.WINDOW_WIDTH,
//                        Constants.WINDOW_HEIGHT,
//                        Image.SCALE_DEFAULT);
        Image mainBak = new ImageIcon("C:\\Users\\dswxl\\Desktop\\remu2.jpg")
                .getImage()
                .getScaledInstance(Constants.WINDOW_WIDTH,
                        Constants.WINDOW_HEIGHT,
                        Image.SCALE_DEFAULT);
    }

    public static void main(String[] args) {
        frame = new JFrame("MainMenu");
//        frame.setContentPane(new GamePanel());
        frame.setContentPane(new MainMenu().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //´°¿Ú¾ÓÖÐ
        frame.setBounds(
                (int) (Toolkit.getDefaultToolkit()
                        .getScreenSize()
                        .getWidth()
                        - Constants.WINDOW_WIDTH) / 2,
                (int) (Toolkit.getDefaultToolkit()
                        .getScreenSize()
                        .getHeight()
                        - Constants.WINDOW_HEIGHT) / 2,
                Constants.WINDOW_WIDTH,
                Constants.WINDOW_HEIGHT);
//        frame.add(new BakPanel());
        frame.setVisible(true);

        jf = new JFrame("Gaming");
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        gamePanel = new GamePanel();
        jf.setContentPane(gamePanel);
        jf.setBounds(
                (int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth() - Constants.WINDOW_WIDTH) / 2,
                (int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight() - Constants.WINDOW_HEIGHT) / 2,
                Constants.WINDOW_WIDTH,
                Constants.WINDOW_HEIGHT);
//        gamePanel.setVisible(true);
//        jf.setVisible(true);


    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new CardLayout(0, 0));
        panel1.setBackground(new Color(-1507841));
        panel1.setOpaque(false);
        panel1.setVisible(true);
        bakPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        bakPanel.setEnabled(false);
        bakPanel.setVisible(true);
        panel1.add(bakPanel, "Card1");
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setOpaque(false);
        bakPanel.add(panel2);
        exitButton = new JButton();
        exitButton.setText("Exit");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(exitButton, gbc);
        startButton = new JButton();
        startButton.setText("Start");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(startButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        bakPanel = new BakPanel();
    }
}
