package com.rabyte.rabitdash.UI;

import com.rabyte.rabitdash.util.RankList;

import javax.swing.*;
import java.awt.*;
import java.util.Vector;

public class RankPanel {
    public JPanel panel1;
    private JTable table1;

    private void createUIComponents() {
        Vector<String> columnNames = new Vector<>();
        Vector<Vector<String>> columnDatas = new Vector();
        columnNames.add("ÐÕÃû");
        columnNames.add("·ÖÊý");

        columnDatas.addAll(RankList.getRankList());
        table1 = new JTable(columnDatas, columnNames);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.NORTH);
        table1.setFocusable(true);
        Font table1Font = this.$$$getFont$$$(null, -1, 14, table1.getFont());
        if (table1Font != null) table1.setFont(table1Font);
        table1.putClientProperty("html.disable", Boolean.TRUE);
        table1.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        scrollPane1.setViewportView(table1);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
